---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-controller-distro-role
rules:
- apiGroups:
  - infrastructure.opendatahub.io
  resources:
  - hardwareprofiles
  verbs:
  - get
  - list
  - watch
