apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: kserve-config-llm-router-route
spec:
  router:
    route:
      http:
        spec:
          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: kserve-ingress-gateway
              namespace: kserve
          rules:
            - backendRefs:
                - group: inference.networking.x-k8s.io
                  kind: InferencePool
                  name: |-
                    {{ ChildName .ObjectMeta.Name `-inference-pool` }}
                  port: 8000
                  weight: 1
              matches:
                - path:
                    type: PathPrefix
                    value: /
              timeouts:
                backendRequest: 0s
                request: 0s
