apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kserve-localmodelnode-agent
  namespace: kserve
  labels:
    app.kubernetes.io/name: kserve-localmodelnode-agent
    control-plane: kserve-localmodelnode-agent
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: kserve-localmodelnode-agent
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kserve-localmodelnode-agent
        control-plane: kserve-localmodelnode-agent
        controller-tools.k8s.io: "1.0"
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      nodeSelector:
        kserve/localmodel: worker
      serviceAccountName: kserve-localmodelnode-agent
      securityContext:
        runAsUser: 0 # TODO: remove this to run as non-root https://issues.redhat.com/browse/RHOAIENG-33247
#        seccompProfile:
#          type: RuntimeDefault
      containers:
      - command:
        - /manager
        image: ko://github.com/kserve/kserve/cmd/localmodelnode
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: true
#          TODO: remove this to run as non-root https://issues.redhat.com/browse/RHOAIENG-33247
#          capabilities:
#            drop:
#              - ALL
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 0
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /mnt/models
            name: models
            readOnly: false
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
        - name: models
          hostPath:
#            path: /models
#            changed to work with Openshift permissions, re-evaluate as a part of https://issues.redhat.com/browse/RHOAIENG-33247
            path: /var/lib/models
            type: DirectoryOrCreate
      terminationGracePeriodSeconds: 10
