apiVersion: v1
kind: Service
metadata:
  name: kserve-module-controller-manager-metrics
  namespace: system
  labels:
    app.kubernetes.io/name: kserve-module-controller-manager
    app.kubernetes.io/component: controller
spec:
  selector:
    control-plane: kserve-module-controller-manager
  ports:
  - name: metrics
    port: 8443
    targetPort: 8443
    protocol: TCP
