apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen3-coder-30b-a3b-instruct
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "multi-nic-compute",
          "namespace": "openshift-sriov-network-operator"
        }
      ]
spec:
  model:
    uri: hf://Qwen/Qwen3-Coder-30B-A3B-Instruct
    name: Qwen/Qwen3-Coder-30B-A3B-Instruct
  replicas: 1
  parallelism:
    data: 16
    dataLocal: 8
    expert: true
    tensor: 1
  router:
    scheduler: { }
    route: { }
    gateway: { }
  template:
    nodeSelector:
      kubernetes.io/hostname: pokprod-b93r38s0
    serviceAccountName: hfsa
    containers:
      - name: main
        env:
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: TRITON_LIBCUDA_PATH
            value: /usr/lib64
          - name: VLLM_SKIP_P2P_CHECK
            value: "1"
          - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
            value: "1"
          - name: VLLM_USE_DEEP_GEMM
            value: "1"
          - name: VLLM_ALL2ALL_BACKEND
            value: deepep_high_throughput
          - name: NVIDIA_GDRCOPY
            value: enabled
          - name: NVSHMEM_DEBUG
            value: INFO
          - name: NVSHMEM_REMOTE_TRANSPORT
            value: ibgda
          - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
            value: net1-15
          - name: GLOO_LOG_LEVEL
            value: DEBUG
          - name: GLOO_SOCKET_IFNAME
            value: net1-15
          - name: NCCL_SOCKET_IFNAME
            value: net1-15
          - name: NCCL_DEBUG
            value: INFO
          - name: NCCL_TIMEOUT
            value: "1800"
          - name: NCCL_ASYNC_ERROR_HANDLING
            value: "1"
          - name: NCCL_IB_TIMEOUT
            value: "23"
          - name: NCCL_IB_RETRY_CNT
            value: "7"
          - name: NVSHMEM_IB_ENABLE_IBGDA
            value: "true"
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NCCL_IB_GID_INDEX
            value: "3"
          - name: NCCL_IB_HCA
            value: "^=mlx5_9,mlx5_8,mlx5_6,mlx5_19,mlx5_17,mlx5_15,mlx5_13,mlx5_10,mlx5_20,mlx5_16,mlx5_12,mlx5_22,mlx5_4,mlx5_0,mlx5_16,mlx5_12,mlx5_5,mlx5_2,mlx5_1,mlx5_23,mlx5_24,mlx5_14,mlx5_3"
        resources:
          limits:
            cpu: 16
            ephemeral-storage: 64Gi
            memory: 512Gi
            nvidia.com/gpu: "8"
            rdma/roce_gdr: 1 # rdma/ib for IB
          requests:
            cpu: 8
            ephemeral-storage: 32Gi
            memory: 256Gi
            nvidia.com/gpu: "8"
            rdma/roce_gdr: 1 # rdma/ib for IB
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 600
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
  worker:
    nodeSelector:
      kubernetes.io/hostname: pokprod-b93r38s2
    serviceAccountName: hfsa
    containers:
      - name: main
        env:
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: TRITON_LIBCUDA_PATH
            value: /usr/lib64
          - name: HF_HUB_DISABLE_XET
            value: "1"
          - name: VLLM_SKIP_P2P_CHECK
            value: "1"
          - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
            value: "1"
          - name: VLLM_USE_DEEP_GEMM
            value: "1"
          - name: VLLM_ALL2ALL_BACKEND
            value: deepep_high_throughput
          - name: NVIDIA_GDRCOPY
            value: enabled
          - name: NVSHMEM_DEBUG
            value: INFO
          - name: NVSHMEM_REMOTE_TRANSPORT
            value: ibgda
          - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
            value: net1-15
          - name: GLOO_LOG_LEVEL
            value: DEBUG
          - name: GLOO_SOCKET_IFNAME
            value: net1-15
          - name: NCCL_SOCKET_IFNAME
            value: net1-15
          - name: NCCL_DEBUG
            value: INFO
          - name: NCCL_TIMEOUT
            value: "1800"
          - name: NCCL_ASYNC_ERROR_HANDLING
            value: "1"
          - name: NCCL_IB_TIMEOUT
            value: "23"
          - name: NCCL_IB_RETRY_CNT
            value: "7"
          - name: NVSHMEM_IB_ENABLE_IBGDA
            value: "true"
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NCCL_IB_GID_INDEX
            value: "3"
          - name: NCCL_IB_HCA
            value: "^=mlx5_2,mlx5_11,mlx5_19,mlx5_3,mlx5_4,mlx5_0,mlx5_8,mlx5_1,mlx5_5,mlx5_13,mlx5_9,mlx5_25,mlx5_21,mlx5_17,mlx5_15,mlx5_23"
        resources:
          limits:
            cpu: 16
            ephemeral-storage: 64Gi
            memory: 512Gi
            nvidia.com/gpu: "8"
            rdma/roce_gdr: 1 # rdma/ib for IB
          requests:
            cpu: 8
            ephemeral-storage: 32Gi
            memory: 256Gi
            nvidia.com/gpu: "8"
            rdma/roce_gdr: 1 # rdma/ib for IB
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 600
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
