apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    leaderworkerset.sigs.k8s.io/subgroup-exclusive-topology: kubernetes.io/hostname
  name: qwen3-30b-a3b-fp8
  namespace: default
spec:
  model:
    name: Qwen/Qwen3-30B-A3B-FP8
    uri: hf://Qwen/Qwen3-30B-A3B-FP8
  parallelism:
    data: 2
    dataLocal: 1
    expert: true
    tensor: 1
  router:
    gateway: { }
    route: { }
    scheduler: { }
  template:
    hostIPC: true
    hostPID: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                    - NVIDIA-H100-80GB-HBM3
    containers:
      - env:
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VLLM_USE_DEEP_GEMM
            value: "0"
          - name: VLLM_ALL2ALL_BACKEND
            value: naive
          - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
            value: "1"
          - name: NCCL_SOCKET_IFNAME
            value: eth0
          - name: NVIDIA_GDRCOPY
            value: enabled
          - name: VLLM_ADDITIONAL_ARGS
            value: "--kv_transfer_config '{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}'"
        name: main
        resources:
          limits:
            cpu: 16
            ephemeral-storage: 64Gi
            memory: 128Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: 8
            ephemeral-storage: 32Gi
            memory: 64Gi
            nvidia.com/gpu: "1"
  worker:
    hostIPC: true
    hostPID: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                    - NVIDIA-H100-80GB-HBM3
    containers:
      - env:
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VLLM_USE_DEEP_GEMM
            value: "0"
          - name: VLLM_ALL2ALL_BACKEND
            value: naive
          - name: NCCL_SOCKET_IFNAME
            value: eth0
          - name: NVIDIA_GDRCOPY
            value: enabled
          - name: VLLM_ADDITIONAL_ARGS
            value: "--kv_transfer_config '{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}'"
        name: main
        resources:
          limits:
            cpu: 16
            ephemeral-storage: 64Gi
            memory: 128Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: 8
            ephemeral-storage: 32Gi
            memory: 64Gi
            nvidia.com/gpu: "1"
