kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: openshift-ai-llminferenceservice-scc
allowPrivilegedContainer: true
allowHostIPC: true
allowHostPID: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowedCapabilities:
  - "IPC_LOCK"
  - "SYS_RAWIO"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-ai-llminferenceservice-scc
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - openshift-ai-llminferenceservice-scc
    verbs:
      - use
