apiVersion: v1
kind: PersistentVolume
metadata:
  name: kserve-localmodelnode-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /var/lib/kserve/models
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kserve/localmodel
              operator: In
              values:
                - worker
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kserve-localmodelnode-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage