apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: kserve-config-llm-template-ibm-spyre
  annotations:
    openshift.io/display-name: vLLM IBM Spyre LLMInferenceServiceConfig
    description: vLLM IBM Spyre LLMInferenceServiceConfig for LLMInferenceService.
spec:
  template:
    containers:
      - name: main
        image: $(kserve-llm-d-ibm-spyre)
