# Copyright 2023 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kserve
from kserve.models.v1alpha2_llm_inference_service_spec import (
    V1alpha2LLMInferenceServiceSpec,
)  # noqa: E501
from kserve.rest import ApiException


class TestV1alpha2LLMInferenceServiceSpec(unittest.TestCase):
    """V1alpha2LLMInferenceServiceSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha2LLMInferenceServiceSpec
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = kserve.models.v1alpha2_llm_inference_service_spec.V1alpha2LLMInferenceServiceSpec()  # noqa: E501
        if include_optional:
            return V1alpha2LLMInferenceServiceSpec(
                base_refs=[None],
                model=kserve.models.v1alpha2
                / llm_model_spec.v1alpha2.LLMModelSpec(
                    lora=kserve.models.v1alpha2
                    / lo_ra_spec.v1alpha2.LoRASpec(
                        adapters=[
                            kserve.models.v1alpha2
                            / llm_model_spec.v1alpha2.LLMModelSpec(
                                name="0",
                                uri=None,
                            )
                        ],
                    ),
                    name="0",
                    uri=None,
                ),
                parallelism=kserve.models.v1alpha2
                / parallelism_spec.v1alpha2.ParallelismSpec(
                    data=56,
                    data_local=56,
                    data_rpc_port=56,
                    expert=True,
                    pipeline=56,
                    tensor=56,
                ),
                prefill=kserve.models.v1alpha2
                / workload_spec.v1alpha2.WorkloadSpec(
                    parallelism=kserve.models.v1alpha2
                    / parallelism_spec.v1alpha2.ParallelismSpec(
                        data=56,
                        data_local=56,
                        data_rpc_port=56,
                        expert=True,
                        pipeline=56,
                        tensor=56,
                    ),
                    replicas=56,
                    template=None,
                    worker=None,
                ),
                replicas=56,
                router=kserve.models.v1alpha2
                / router_spec.v1alpha2.RouterSpec(
                    gateway=kserve.models.v1alpha2
                    / gateway_spec.v1alpha2.GatewaySpec(
                        refs=[
                            kserve.models.v1alpha2
                            / untyped_object_reference.v1alpha2.UntypedObjectReference(
                                name="0",
                                namespace="0",
                            )
                        ],
                    ),
                    ingress=kserve.models.v1alpha2
                    / ingress_spec.v1alpha2.IngressSpec(),
                    route=kserve.models.v1alpha2
                    / gateway_routes_spec.v1alpha2.GatewayRoutesSpec(
                        http=kserve.models.v1alpha2
                        / http_route_spec.v1alpha2.HTTPRouteSpec(
                            spec=None,
                        ),
                    ),
                    scheduler=kserve.models.v1alpha2
                    / scheduler_spec.v1alpha2.SchedulerSpec(
                        pool=kserve.models.v1alpha2
                        / inference_pool_spec.v1alpha2.InferencePoolSpec(
                            ref=None,
                            spec=None,
                        ),
                        template=None,
                    ),
                ),
                template=None,
                worker=None,
            )
        else:
            return V1alpha2LLMInferenceServiceSpec()

    def testV1alpha2LLMInferenceServiceSpec(self):
        """Test V1alpha2LLMInferenceServiceSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
