# Adds conversion webhook configuration to LLMInferenceService CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: llminferenceservices.serving.kserve.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kserve-webhook-server-service
          namespace: kserve
          path: /convert
      conversionReviewVersions:
        - v1
        - v1beta1