---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/feast?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "group-test"
    pipelinesascode.tekton.dev/on-comment: "^/group-test"
  name: kserve-group-test
  namespace: open-data-hub-tenant
  labels:
    appstudio.openshift.io/application: group-testing
    appstudio.openshift.io/component: kserve-group
    pipelines.appstudio.openshift.io/type: test
spec:
  params:
  - name: group-components
    value: '{ "kserve-agent-ci": "opendatahub/kserve-agent", "kserve-controller-ci": "opendatahub/kserve-controller", "kserve-router-ci": "opendatahub/kserve-router", "kserve-storage-initializer-ci": "opendatahub/kserve-storage-initializer" }'
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: main
    - name: pathInRepo
      value: integration-tests/kserve/pr-group-testing-pipeline.yaml
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        konflux-ci.dev/workload: konflux-tenants
      tolerations:
      - effect: NoSchedule
        key: konflux-ci.dev/workload
        operator: Equal
        value: konflux-tenants
    serviceAccountName: konflux-integration-runner
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'