# Copyright 2023 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kserve.configuration import Configuration


class V1alpha2RouterSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'gateway': 'V1alpha2GatewaySpec',
        'ingress': 'V1alpha2IngressSpec',
        'route': 'V1alpha2GatewayRoutesSpec',
        'scheduler': 'V1alpha2SchedulerSpec'
    }

    attribute_map = {
        'gateway': 'gateway',
        'ingress': 'ingress',
        'route': 'route',
        'scheduler': 'scheduler'
    }

    def __init__(self, gateway=None, ingress=None, route=None, scheduler=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha2RouterSpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._gateway = None
        self._ingress = None
        self._route = None
        self._scheduler = None
        self.discriminator = None

        if gateway is not None:
            self.gateway = gateway
        if ingress is not None:
            self.ingress = ingress
        if route is not None:
            self.route = route
        if scheduler is not None:
            self.scheduler = scheduler

    @property
    def gateway(self):
        """Gets the gateway of this V1alpha2RouterSpec.  # noqa: E501


        :return: The gateway of this V1alpha2RouterSpec.  # noqa: E501
        :rtype: V1alpha2GatewaySpec
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this V1alpha2RouterSpec.


        :param gateway: The gateway of this V1alpha2RouterSpec.  # noqa: E501
        :type: V1alpha2GatewaySpec
        """

        self._gateway = gateway

    @property
    def ingress(self):
        """Gets the ingress of this V1alpha2RouterSpec.  # noqa: E501


        :return: The ingress of this V1alpha2RouterSpec.  # noqa: E501
        :rtype: V1alpha2IngressSpec
        """
        return self._ingress

    @ingress.setter
    def ingress(self, ingress):
        """Sets the ingress of this V1alpha2RouterSpec.


        :param ingress: The ingress of this V1alpha2RouterSpec.  # noqa: E501
        :type: V1alpha2IngressSpec
        """

        self._ingress = ingress

    @property
    def route(self):
        """Gets the route of this V1alpha2RouterSpec.  # noqa: E501


        :return: The route of this V1alpha2RouterSpec.  # noqa: E501
        :rtype: V1alpha2GatewayRoutesSpec
        """
        return self._route

    @route.setter
    def route(self, route):
        """Sets the route of this V1alpha2RouterSpec.


        :param route: The route of this V1alpha2RouterSpec.  # noqa: E501
        :type: V1alpha2GatewayRoutesSpec
        """

        self._route = route

    @property
    def scheduler(self):
        """Gets the scheduler of this V1alpha2RouterSpec.  # noqa: E501


        :return: The scheduler of this V1alpha2RouterSpec.  # noqa: E501
        :rtype: V1alpha2SchedulerSpec
        """
        return self._scheduler

    @scheduler.setter
    def scheduler(self, scheduler):
        """Sets the scheduler of this V1alpha2RouterSpec.


        :param scheduler: The scheduler of this V1alpha2RouterSpec.  # noqa: E501
        :type: V1alpha2SchedulerSpec
        """

        self._scheduler = scheduler

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha2RouterSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha2RouterSpec):
            return True

        return self.to_dict() != other.to_dict()
