# Copyright 2023 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kserve.configuration import Configuration


class V1alpha1LocalModelCacheStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'copies': 'V1alpha1ModelCopies',
        'inference_services': 'list[V1alpha1NamespacedName]',
        'node_status': 'dict(str, str)'
    }

    attribute_map = {
        'copies': 'copies',
        'inference_services': 'inferenceServices',
        'node_status': 'nodeStatus'
    }

    def __init__(self, copies=None, inference_services=None, node_status=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1LocalModelCacheStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._copies = None
        self._inference_services = None
        self._node_status = None
        self.discriminator = None

        if copies is not None:
            self.copies = copies
        if inference_services is not None:
            self.inference_services = inference_services
        if node_status is not None:
            self.node_status = node_status

    @property
    def copies(self):
        """Gets the copies of this V1alpha1LocalModelCacheStatus.  # noqa: E501


        :return: The copies of this V1alpha1LocalModelCacheStatus.  # noqa: E501
        :rtype: V1alpha1ModelCopies
        """
        return self._copies

    @copies.setter
    def copies(self, copies):
        """Sets the copies of this V1alpha1LocalModelCacheStatus.


        :param copies: The copies of this V1alpha1LocalModelCacheStatus.  # noqa: E501
        :type: V1alpha1ModelCopies
        """

        self._copies = copies

    @property
    def inference_services(self):
        """Gets the inference_services of this V1alpha1LocalModelCacheStatus.  # noqa: E501

        Inference services using this local model  # noqa: E501

        :return: The inference_services of this V1alpha1LocalModelCacheStatus.  # noqa: E501
        :rtype: list[V1alpha1NamespacedName]
        """
        return self._inference_services

    @inference_services.setter
    def inference_services(self, inference_services):
        """Sets the inference_services of this V1alpha1LocalModelCacheStatus.

        Inference services using this local model  # noqa: E501

        :param inference_services: The inference_services of this V1alpha1LocalModelCacheStatus.  # noqa: E501
        :type: list[V1alpha1NamespacedName]
        """

        self._inference_services = inference_services

    @property
    def node_status(self):
        """Gets the node_status of this V1alpha1LocalModelCacheStatus.  # noqa: E501

        Status of the model on a node, like NodeDownloaded or NodeNotReady  # noqa: E501

        :return: The node_status of this V1alpha1LocalModelCacheStatus.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._node_status

    @node_status.setter
    def node_status(self, node_status):
        """Sets the node_status of this V1alpha1LocalModelCacheStatus.

        Status of the model on a node, like NodeDownloaded or NodeNotReady  # noqa: E501

        :param node_status: The node_status of this V1alpha1LocalModelCacheStatus.  # noqa: E501
        :type: dict(str, str)
        """

        self._node_status = node_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1LocalModelCacheStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1LocalModelCacheStatus):
            return True

        return self.to_dict() != other.to_dict()
