# Copyright 2023 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kserve.configuration import Configuration


class V1alpha1PoolStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "conditions": "list[V1Condition]",
        "parent_ref": "V1alpha1ParentGatewayReference",
    }

    attribute_map = {"conditions": "conditions", "parent_ref": "parentRef"}

    def __init__(
        self, conditions=None, parent_ref=None, local_vars_configuration=None
    ):  # noqa: E501
        """V1alpha1PoolStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._conditions = None
        self._parent_ref = None
        self.discriminator = None

        if conditions is not None:
            self.conditions = conditions
        self.parent_ref = parent_ref

    @property
    def conditions(self):
        """Gets the conditions of this V1alpha1PoolStatus.  # noqa: E501

        Conditions track the state of the InferencePool.  Known condition types are:  * \"Accepted\" * \"ResolvedRefs\"  # noqa: E501

        :return: The conditions of this V1alpha1PoolStatus.  # noqa: E501
        :rtype: list[V1Condition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this V1alpha1PoolStatus.

        Conditions track the state of the InferencePool.  Known condition types are:  * \"Accepted\" * \"ResolvedRefs\"  # noqa: E501

        :param conditions: The conditions of this V1alpha1PoolStatus.  # noqa: E501
        :type: list[V1Condition]
        """

        self._conditions = conditions

    @property
    def parent_ref(self):
        """Gets the parent_ref of this V1alpha1PoolStatus.  # noqa: E501


        :return: The parent_ref of this V1alpha1PoolStatus.  # noqa: E501
        :rtype: V1alpha1ParentGatewayReference
        """
        return self._parent_ref

    @parent_ref.setter
    def parent_ref(self, parent_ref):
        """Sets the parent_ref of this V1alpha1PoolStatus.


        :param parent_ref: The parent_ref of this V1alpha1PoolStatus.  # noqa: E501
        :type: V1alpha1ParentGatewayReference
        """
        if (
            self.local_vars_configuration.client_side_validation and parent_ref is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `parent_ref`, must not be `None`"
            )  # noqa: E501

        self._parent_ref = parent_ref

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1PoolStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1PoolStatus):
            return True

        return self.to_dict() != other.to_dict()
