/*
Copyright 2023 The KServe Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	servingv1alpha2 "github.com/kserve/kserve/pkg/apis/serving/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LLMInferenceServiceConfigLister helps list LLMInferenceServiceConfigs.
// All objects returned here must be treated as read-only.
type LLMInferenceServiceConfigLister interface {
	// List lists all LLMInferenceServiceConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*servingv1alpha2.LLMInferenceServiceConfig, err error)
	// LLMInferenceServiceConfigs returns an object that can list and get LLMInferenceServiceConfigs.
	LLMInferenceServiceConfigs(namespace string) LLMInferenceServiceConfigNamespaceLister
	LLMInferenceServiceConfigListerExpansion
}

// lLMInferenceServiceConfigLister implements the LLMInferenceServiceConfigLister interface.
type lLMInferenceServiceConfigLister struct {
	listers.ResourceIndexer[*servingv1alpha2.LLMInferenceServiceConfig]
}

// NewLLMInferenceServiceConfigLister returns a new LLMInferenceServiceConfigLister.
func NewLLMInferenceServiceConfigLister(indexer cache.Indexer) LLMInferenceServiceConfigLister {
	return &lLMInferenceServiceConfigLister{listers.New[*servingv1alpha2.LLMInferenceServiceConfig](indexer, servingv1alpha2.Resource("llminferenceserviceconfig"))}
}

// LLMInferenceServiceConfigs returns an object that can list and get LLMInferenceServiceConfigs.
func (s *lLMInferenceServiceConfigLister) LLMInferenceServiceConfigs(namespace string) LLMInferenceServiceConfigNamespaceLister {
	return lLMInferenceServiceConfigNamespaceLister{listers.NewNamespaced[*servingv1alpha2.LLMInferenceServiceConfig](s.ResourceIndexer, namespace)}
}

// LLMInferenceServiceConfigNamespaceLister helps list and get LLMInferenceServiceConfigs.
// All objects returned here must be treated as read-only.
type LLMInferenceServiceConfigNamespaceLister interface {
	// List lists all LLMInferenceServiceConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*servingv1alpha2.LLMInferenceServiceConfig, err error)
	// Get retrieves the LLMInferenceServiceConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*servingv1alpha2.LLMInferenceServiceConfig, error)
	LLMInferenceServiceConfigNamespaceListerExpansion
}

// lLMInferenceServiceConfigNamespaceLister implements the LLMInferenceServiceConfigNamespaceLister
// interface.
type lLMInferenceServiceConfigNamespaceLister struct {
	listers.ResourceIndexer[*servingv1alpha2.LLMInferenceServiceConfig]
}
